config/routes.rb
Rails.application.routes.draw do
	resources :drinks
  resources :genres, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
	belongs_to :genre
	attachment :image
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :drinks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

def new
  	@drink = Drink.new
  end

  def create
  	drink = Drink.new(drink_params)
  	drink.save
  	redirect_to drinks_path
  end

  def index
  	@drink = Drink.all
	@genres = Genre.all
		# urlにcategory_id(params)がある場合
        if params[:genre_id]
		    # Categoryのデータベースのテーブルから一致するidを取得
		    @genre = Genre.find(params[:genre_id])
		    # category_idと紐づく投稿を取得
		    @drinks = @genre.drinks.order(created_at: :desc).all.page(params[:page]).per(8)
		else
		    # 投稿すべてを取得
	        @drinks = Drink.order(created_at: :desc).all.page(params[:page]).per(8)
    	end
  end

  def show
  	@drink = Drink.find(params[:id])
  end

  def edit
  	@drink = Drink.find(params[:id])
  end

  def update
  	drink = Drink.find(params[:id])
  	drink.update(drink_params)
  	redirect_to drink_path(drink.id)
  end

  def destroy
  	@drink = Drink.find(params[:id])
  	@drink.destroy
  	redirect_to drinks_path
  end

  private
  	def drink_params
  	params.require(:drink).permit(:drink_name, :image, :body, :genre_id )
  	end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

	def new
		@genre = Genre.new
	end
	def create
		genre = Genre.new(genre_params)

		#####
		genre_check = Genre.find_by(name: genre.name)
		if genre_check == nil
			# 名前が存在しない
			genre.save
			redirect_to drinks_path
		else
			# 名前がすでに存在する
			# なんかえらーの処理
			flash[:error] = "すでに存在するジャンルです。"
			redirect_to new_genre_path
		end
	end

	private
  	def genre_params
  	params.require(:genre).permit(:name)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/drinks/edit.html.erb
<div class="row">
	<div class="text-center">
		<%= form_for(@drink) do |f| %>
		<h2>Drink Name</h2>
		<div class="black"><%= f.text_field :drink_name %></div>
		<h2>Details</h2>
		<div class="black"><%= f.text_area :body %></div>
		<h2>Genre</h2>
		<div class="black"><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "選択して下さい" %></div>
			<div class="col-xs-5"></div>
			<div class="col-xs-7">
				<%= f.attachment_field :image %><br>
				<%= f.submit '投稿', class: "btn btn-primary col-xs-3" %>
			</div>
		<% end %>
	</div>
</div>

app/views/drinks/index.html.erb
<div class="title">
	<h1 class="text-center">Drink Menu</h1>
</div>

<div class="row">
	<div class="col-xs-1"></div>
	<div class="col-xs-2">
		<div class="genre">
			<h5>ジャンルで探す</h5>
			<h5><%= link_to "すべてのジャンル", drinks_path %></h5></h5>
			<% @genres.each do |genre| %>
				<h5 class="genrelist"><%= link_to genre.name, drinks_path(genre_id: genre.id) %></h5>
			<% end %>
		</div>
	</div>
	<div class="col-xs-9">
		<% if params[:genre_id] %>
		    <div class="drink-title"><h4><%= @genre.name %></h4><p>(全<%= @drinks.count %>件)</p></div>
		<% else %>
		　　　<div class="drink-title-all"><h4>すべてのジャンル</h4><p>(全<%= @drinks.count %>件)</p></div>
		<% end %>

		<% @drinks.each do |drink| %>
			<div class="drink">
				<%= link_to drink_path(drink.id) do %>
	    			<figure class="drink-image"><%= attachment_image_tag(drink, :image, :fill, 200, 200)%></figure>
	    		<% end %><br>
	    		<p><%= drink.drink_name %></p>
			</div>
		<% end %>
	</div>
</div>

app/views/drinks/new.html.erb
<div class="row">
	<div class="text-center">
		<h1>New Drink</h1>
		<%= form_for(@drink) do |f| %>
		<h2>Drink Name</h2>
		<div class="black"><%= f.text_field :drink_name %></div>
		<h2>Details</h2>
			<div class="black"><%= f.text_area :body %></div>
		<h2>Genre</h2>
		<div class="black"><%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "選択して下さい" %></div><br>
			<div class="col-xs-5"></div>
			<div class="col-xs-7">
				<%= f.attachment_field :image %><br>
				<%= f.submit '投稿', class: "btn btn-primary col-xs-3" %>
			</div>
		<% end %>
	</div>
</div>

app/views/drinks/show.html.erb
<div class="show_title">
	<h1>Drink</h1>
<%= @drink.drink_name %><br>
<%= attachment_image_tag(@drink, :image, :fill, 500, 500)%><br>
<%= simple_format(@drink.body) %><br>
<%= link_to "編集", edit_drink_path(@drink.id), class: "btn btn-info "  %>
<%= link_to "削除", drink_path, method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn btn-danger"  %><br>
</div>

app/views/genres/new.html.erb
<div class="text-center">
<h1>Drink Genre</h1>

<% if flash[:error] %>
  <div class="flash">
    <%= flash[:error] %>
  </div>
<% end %>

<%= form_for(@genre) do |f| %>
<h2>genre Name</h2>
<div class="black"><%= f.text_field :name %></div><br>
<div class="col-xs-5"></div>
			<div class="col-xs-7">
				<%= f.submit '投稿', class: "btn btn-primary col-xs-3" %>
			</div>
<% end %>
</div>

app/views/home/index.html.erb
<div class="topimage">
	<h1>Grandma</h1>
	<p>グランマ</p>
	<div class="push">
		<%= link_to "lets go!", drinks_path %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grandma2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse bg-dark" >
     <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-dark">
          <li>
            <%= link_to "Top page", root_path %>
          </li>
          <li>
            <%= link_to "New Drink", new_drink_path %>
          </li>
          <li>
            <%= link_to "Drink List", drinks_path %>
          </li>
          <li>
            <%= link_to "New Genre", new_genre_path %>
          </li>
        </ul>
      </nav>
     </div>
    </header>
    <%= yield %>
  </body>
</html>